export const emojiMap = {
    ":smile:": "😀",
    ":laughing:": "😆",
    ":wink:": "😉",
    ":heart:": "❤️",
    ":thumbsup:": "👍",
    ":star:": "⭐",
    ":fire:": "🔥",
    ":rocket:": "🚀",
    ":coffee:": "☕",
    ":check:": "✔️",
    ":x:": "❌",
    ":warning:": "⚠️",
    ":question:": "❓",
    ":exclamation:": "❗",
    ":js:": '<span class="character-image js-icon"></span>',
    ":html:": '<span class="character-image html-icon"></span>',
    ":css:": '<span class="character-image css-icon"></span>',
    ":bash:": '<span class="character-image bash-icon"></span>',
    ":c:": '<span class="character-image c-icon"></span>',
    ":cpp:": '<span class="character-image cpp-icon"></span>',
    ":csharp:": '<span class="character-image csharp-icon"></span>',
    ":go:": '<span class="character-image go-icon"></span>',
    ":java:": '<span class="character-image java-icon"></span>',
    ":json:": '<span class="character-image json-icon"></span>',
    ":md:": '<span class="character-image md-icon"></span>',
    ":php:": '<span class="character-image php-icon"></span>',
    ":python:": '<span class="character-image python-icon"></span>',
    ":regex:": '<span class="character-image regex-icon"></span>',
    ":ts:": '<span class="character-image ts-icon"></span>',
    ":xml:": '<span class="character-image xml-icon"></span>',
    ":yaml:": '<span class="character-image yaml-icon"></span>',
    ":scratch:": '<span class="character-image scratch-icon"></span>',
    ":spacetode:": '<span class="character-image spacetode-icon"></span>',
    ":haskell:": '<span class="character-image haskell-icon"></span>',
    ":tidalcycles:": '<span class="character-image tidalcycles-icon"></span>',
    ":clojure:": '<span class="character-image clojure-icon"></span>',
    ":fsharp:": '<span class="character-image fsharp-icon"></span>',
    ":brainfuck:": '<span class="character-image brainfuck-icon"></span>',
    ":piet:": '<span class="character-image piet-icon"></span>',
    ":lua:": '<span class="character-image lua-icon"></span>',
    ":powershell:": '<span class="character-image powershell-icon"></span>',
};
